name: Gen Keystore

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Generate release keystore
        run: |
          keytool -genkeypair -v \
            -keystore qr-release.jks \
            -storetype JKS \
            -alias qrscanner \
            -keyalg RSA -keysize 2048 -validity 10950 \
            -storepass 'QrScan@13528490965' -keypass 'QrScan@13528490965' \
            -dname "CN=QRScanner, OU=Mobile, O=QRScanner, L=Shenzhen, ST=Guangdong, C=CN"

      - uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: qr-release.jks
